In [ ]:
 import numpy as np

In [ ]:
 mylist = [1,2,3]

In [ ]:
np.array(mylist)

array([1, 2, 3])

In [ ]:
nested_list = [[1,2],[3,4],[5,6]]

In [ ]:
nested_list

[[1, 2], [3, 4], [5, 6]]

In [ ]:
np.array(nested_list)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [ ]:
np.zeros(3)

array([0., 0., 0.])

In [ ]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.ones(3)

array([1., 1., 1.])

In [ ]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.linspace(0,10,21)

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [ ]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np.random.rand(2)

array([0.52044707, 0.63441584])

In [ ]:
np.random.rand(3,4)

array([[0.35443035, 0.95940486, 0.8728751 , 0.64171562],
       [0.59726279, 0.90942711, 0.39795092, 0.40930351],
       [0.50139975, 0.38614408, 0.78190303, 0.50990075]])

In [ ]:
np.random.randn(5,5)

array([[ 0.21313162,  0.99151411, -1.5223634 ,  0.63265779,  0.10419497],
       [-0.70050953,  0.24782365, -0.64991019, -1.08885059, -0.02799526],
       [-0.82083351, -0.94593277, -0.54616942, -0.41202884,  0.53970966],
       [-0.90194056,  0.06735495,  0.25650026,  1.81649331, -1.19771555],
       [ 0.45207859,  0.04185908,  0.0363701 ,  1.19259772,  1.10686779]])

In [ ]:
np.random.randint(1,100,(2,3))

array([[68, 79,  2],
       [15, 78, 77]])

In [ ]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [ ]:
arr = np.arange(25)

In [ ]:
ranarr = np.random.randint(6,50,10)

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
ranarr

array([44, 24, 28, 16, 16, 29, 41, 45, 29,  8])

In [ ]:
arr.shape

(25,)

In [ ]:
arr = arr.reshape(5,5)

In [ ]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
ranarr.max()

45

In [ ]:
ranarr.argmax()

7

In [ ]:
ranarr.argmin()

9

In [ ]:
ranarr.dtype

dtype('int64')

In [ ]:
myarr = np.random.rand(4)

In [ ]:
myarr

array([0.02058449, 0.96990985, 0.83244264, 0.21233911])

In [ ]:
myarr.dtype

dtype('float64')