In [ ]:
import numpy as np

In [ ]:
arr = np.arange(0,11)

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr[8]

8

In [ ]:
arr[1:5]

array([1, 2, 3, 4])

In [ ]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [ ]:
arr[:5]

array([0, 1, 2, 3, 4])

In [ ]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [ ]:
arr[0:5] = 100

In [ ]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [ ]:
arr = np.arange(0,11)

In [ ]:
slice_of_arr = arr[0:5]

In [ ]:
slice_of_arr

array([0, 1, 2, 3, 4])

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
slice_of_arr[:]= 99

In [ ]:
slice_of_arr

array([99, 99, 99, 99, 99])

In [ ]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [ ]:
arr_copy = arr.copy()

In [ ]:
arr_copy[:] = 100

In [ ]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [ ]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [ ]:
arr2d = np.array([[5,10,15], [20,25,30], [35,40,45]])

In [ ]:
arr2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [ ]:
arr2d.shape

(3, 3)

In [ ]:
arr2d[2]

array([35, 40, 45])

In [ ]:
arr2d[1][1]

25

In [ ]:
arr2d[1,1]

25

In [ ]:
arr2d[0,2]

15

In [ ]:
arr2d[:2, 1:]

array([[10, 15],
       [25, 30]])

In [ ]:
arr = np.arange(1,11)

In [ ]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [ ]:
bool_arr = arr>4

In [ ]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [ ]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [ ]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])